application:
  name: aria2-ariang-docker-master
  project: Ariang
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: aria2-ariang-docker-master
    paths:
    - /
